# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70f2026e7792a4289ec6598a8fbc8e86a75ccdb18cf20dde3d9e77bef52ae4bbbd5c5cc162d6fc4134b8ae1e1647d26793d1f75a89ed3ccfa76b69440e5a496d

test:
  secret_key_base: 244c984c397738dfa1f17be66445ca3fb619ce16eb86bfe649a6316a6ca0fb5489153879dfafa5a7e646de9673d5c378e310963bdcf48cb22e54405f82300eba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
